-- CREATE TABLE "stocks" (
--     id INTEGER PRIMARY KEY UNIQUE NOT NULL,
--     user_id SERIAL NOT NULL,
--     symbol CHAR(15) NOT NULL,
--     shares INT UNSIGNED NOT NULL DEFAULT 1,
--     FOREIGN KEY (user_id) REFERENCES users(id)
-- );

-- CREATE history (
    -- id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    -- user_id SERIAL NOT NULL,
    -- type TEXT NOT NULL,
    -- symbol CHAR(15) NOT NULL
    -- shares INT UNSIGNED NOT NULL,
    -- FOREIGN KEY (user_id) REFERENCES users(id)
-- );
